# simple, cooking, coin, treasure
task: "cooking"

simple:
  game_file_path: "./data/simple/mock_game/"
  walkthroughs_file_path: "./data/simple/walkthroughs/"
  oracle_file_path: "./data/simple/oracle_dense/"
  lm_file_path: "./data/simple/lm/"
  model_save_path: "./model/critic/simple/dense"
  checkpoint_interval: 10
  num_epochs: 50
  batch_size: 32
  device: "cuda"
  bert_path: "./bert/"
  seed: 123466
  validate_file_path: "./simple_test/simple"
  sampling_strategy: "fixed"
  reward_sample_ratio: 0.6
  dynamic_ratio_min: 0.4
  dynamic_ratio_max: 0.8
  dynamic_step: 0.05

cooking:
  game_file_path: "./data/cooking/mock_game/"
  walkthroughs_file_path: "./data/cooking/walkthroughs/"
  oracle_file_path: "./data/cooking/oracle/"
  lm_file_path: "./data/cooking/lm/"
  random_file_path: "./data/cooking/random/"
  model_save_path: "./model/critic/cooking/dynamic"
  checkpoint_interval: 10
  num_epochs: 50
  batch_size: 32
  device: "cuda"
  bert_path: "./bert/"
  seed: 1224
  validate_file_path: "./simple_test/cooking"
  sampling_strategy: "dynamic"
  reward_sample_ratio: 0.5
  dynamic_ratio_min: 0.2
  dynamic_ratio_max: 0.9
  dynamic_step: 0.05

coin:
  game_file_path: "./data/coin/mock_game/"
  walkthroughs_file_path: "./data/coin/walkthroughs/"
  oracle_file_path: "./data/coin/oracle/"
  lm_file_path: "./data/coin/lm/"
  model_save_path: "./model/critic/coin/"
  checkpoint_interval: 10
  num_epochs: 100
  batch_size: 32
  device: "cuda"
  bert_path: "./bert/"
  seed: 1224
  validate_file_path: "./simple_test/coin"
  sampling_strategy: "fixed"
  reward_sample_ratio: 0.5
  dynamic_ratio_min: 0.3
  dynamic_ratio_max: 0.9
  dynamic_step: 0.05


treasure:
  game_file_path: "./data/treasure/mock_game/"
  walkthroughs_file_path: "./data/treasure/walkthroughs/"
  oracle_file_path: "./data/treasure/oracle/"
  lm_file_path: "./data/treasure/lm/"
  model_save_path: "./model/critic/treasure/dynamic"
  checkpoint_interval: 10
  num_epochs: 100
  batch_size: 32
  device: "cuda"
  bert_path: "./bert/"
  seed: 1234
  validate_file_path: "./simple_test/treasure"
  sampling_strategy: "dynamic"
  reward_sample_ratio: 0.6
  dynamic_ratio_min: 0.3
  dynamic_ratio_max: 0.9
  dynamic_step: 0.04
