game_file_path: "./data/simple/mock_game/"
walkthroughs_file_path: "./data/simple/walkthroughs/"
oracle_file_path: "./data/simple/oracle/"
lm_file_path: "./data/simple/lm/"
model_save_path: "./model/critic"
checkpoint_interval: 10
num_epochs: 128
batch_size: 16
device: "cuda"
bert_path: "./bert/"